name: easy_cook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  file_picker: ^3.0.0
  photo: ^0.4.8
  http: ^0.13.1
 

  path: ^1.7.0

  shared_preferences: ^2.0.8

  mime: ^1.0.0



  #อันนี้
  chewie: ^1.2.2
  video_player: ^2.2.4

  #อัน2
  # chewie: ^1.0.0
  # video_player: ^2.0.0

  # chewie: ^1.0.0
  # video_player: ^2.1.2

  flutter_typeahead: ^3.1.0
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.7.4

  page_transition: ^1.1.7+6

  
  cupertino_icons: ^1.0.3
 
  curved_navigation_bar: ^0.3.4
 
  sliver_fab: ^1.0.0

  rflutter_alert: ^1.0.3
  
 


  implicitly_animated_reorderable_list: ^0.4.0

  image_cropper: ^1.3.1

   
  progress_state_button: ^1.0.2 # ปุ่ม อนิเมชั่น โหลด

  flutter_rating_bar: ^3.2.0+1

 

  google_fonts: ^2.1.0

  inview_notifier_list: ^2.0.0

  flutter_native_splash: ^1.2.0

  intl: ^0.17.0

  firebase_core: ^1.4.0
  flutter_local_notifications: ^8.1.1
  firebase_messaging: ^10.0.4
  
  flutter_launcher_icons: ^0.9.1
  
  form_field_validator: ^1.1.0
  email_validator: '^1.0.6'

  flutter_credit_card: ^2.0.0

  flutter_facebook_login: ^3.0.0

  flutter_signin_button: ^2.0.0

  translator: ^0.1.7

  flutter_svg: ^0.22.0

  dio: ^4.0.0
  path_provider: ^2.0.2

  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  
  image_gallery_saver: ^1.6.9

  fluttertoast: ^8.0.8
  
  animated_text_kit: ^4.2.1

  flutter_slidable: ^0.6.0

  flutter_offline: ^2.0.0
  flutter_tindercard: ^0.2.0
  
  readmore: ^2.1.0

  # story_view: ^0.9.3
  story_view: ^0.13.1

  flutter_tts: ^3.2.2

  share: ^2.0.4
  
  
  # emoji_picker: ^0.0.2
  
  # emoji_picker: ^0.1.0
  # rxdart: ^0.25.0
  # rounded_loading_button: ^1.0.18

  # provider: ^5.0.0
  google_sign_in: ^5.1.1
  firebase_auth: ^1.1.4
  
  better_player: ^0.0.76

  video_thumbnail: ^0.4.3

  qr_flutter: ^4.0.0
  pattern_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/Easy_Cook.png
  android_disable_fullscreen: true
  # android_gravity: fill

flutter_icons:
  android: true
  image_path: "assets/logos/hamburger.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/user.png
    - assets/images/
    - assets/logos/
    - assets/loadGif/
    - assets/topupQRcode/
    - assets/wallpapers/
    - assets/iconFood/
    - assets/logoLogin/
    - assets/logoSearch/
    - assets/logoNoti/
    - assets/imageSearch/
 
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        # - asset: fonts/OpenSans.ttf
        - asset: fonts/Mali-Light.ttf
          
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
