name: easy_cook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #image_picker: ^0.7.2
  # image_picker: ^0.6.7+22
  file_picker: ^3.0.0
  photo: ^0.4.8
  http: ^0.13.1
 
  # sqflite: ^1.3.2+4
  path: ^1.7.0
  shared_preferences: ^2.0.4
  # dio: ^3.0.10
  mime: ^0.9.7 
  # chewie: ^0.12.2
  # video_player: ^1.0.1
  chewie: ^1.2.2
  video_player: ^2.1.14
  
  flutter_typeahead: ^3.1.0
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.7.4
  # image_picker: ^0.6.7+22
  rxdart: ^0.25.0
  # image_picker: ^0.7.3
  # file_picker: ^3.0.0
  # loading: ^1.0.2 #test
  # dio: ^2.2.2
  # flutter_secure_storage: ^3.3.3
  page_transition: ^1.1.7+6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
 
  curved_navigation_bar: ^0.3.4
  # file_picker: ^2.1.3
  sliver_fab: ^1.0.0

  rflutter_alert: ^1.0.3
  # rounded_loading_button: ^2.0.3
  rounded_loading_button: ^1.0.18

  # reorderables: ^0.4.1
  implicitly_animated_reorderable_list: ^0.4.0

  image_cropper: ^1.3.1

   
  progress_state_button: ^1.0.2 # ปุ่ม อนิเมชั่น โหลด

  flutter_rating_bar: ^3.2.0+1

  readmore: ^1.0.0

  google_fonts: ^2.1.0

  inview_notifier_list: ^2.0.0

  flutter_native_splash: ^1.2.0

  intl: ^0.17.0

  firebase_core: ^1.4.0
  flutter_local_notifications: ^8.1.1
  firebase_messaging: ^10.0.4
  
  flutter_launcher_icons: ^0.9.1

  email_validator: '^1.0.6'

  flutter_credit_card: ^2.0.0

  flutter_facebook_login: ^3.0.0

  flutter_signin_button: ^2.0.0

  translator: ^0.1.7

  flutter_svg: ^0.22.0

  dio: ^4.0.0
  path_provider: ^2.0.2

  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  
  image_gallery_saver: ^1.6.9

  fluttertoast: ^8.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/Easy_Cook.png
  android_disable_fullscreen: true
  # android_gravity: fill

flutter_icons:
  android: true
  image_path: "assets/logos/hamburger.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/user.png
    - assets/images/
    - assets/logos/
    - assets/loadGif/
    - assets/topupQRcode/
    - assets/wallpapers/
    # - assets/logos/facebook.jpg
    # - assets/logos/drink.png
    # - assets/logos/vegetables.png
    # - assets/logos/steam.png
    # - assets/logos/stew.png
    # - assets/logos/fried.png
    # - assets/logos/pot .png
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
